/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual1;

/**
 *
 * @author sstem
 */
public class DatosPersonalesEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form DatosPersonalesEstudiantes
     */
    public DatosPersonalesEstudiantes() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        titlePanel = new rspanelgradiente.RSPanelGradiente();
        lblTitle = new javax.swing.JLabel();
        sidePanel = new rspanelgradiente.RSPanelGradiente();
        imgUtecLogo = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JPanel();
        imgBtnUsuario = new javax.swing.JLabel();
        lblBtnUsuario = new javax.swing.JLabel();
        btnReclamos = new javax.swing.JPanel();
        imgBtnReclamos = new javax.swing.JLabel();
        lblBtnReclamos = new javax.swing.JLabel();
        btnInasistencias = new javax.swing.JPanel();
        imgBtnJustificaciones = new javax.swing.JLabel();
        lblBtnJustificaciones = new javax.swing.JLabel();
        btnInasistencias1 = new javax.swing.JPanel();
        imgBtnJustificaciones1 = new javax.swing.JLabel();
        lblBtnJustificaciones1 = new javax.swing.JLabel();
        jLabelRuta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelprimerApellido = new javax.swing.JLabel();
        jLabelPrimerNombre = new javax.swing.JLabel();
        jCTextFieldPrimerNombre = new app.bolivia.swing.JCTextField();
        jCTextPrimerApellido = new app.bolivia.swing.JCTextField();
        jCTextFechaNacimiento = new app.bolivia.swing.JCTextField();
        jLabelFechaDeNacimiento = new javax.swing.JLabel();
        jLabelSegundoNombre = new javax.swing.JLabel();
        jCTextSegundoNombre = new app.bolivia.swing.JCTextField();
        jLabelSegundoApellido = new javax.swing.JLabel();
        jCTextSegundoApellido = new app.bolivia.swing.JCTextField();
        jLabelGenero = new javax.swing.JLabel();
        jCTextGenero = new app.bolivia.swing.JCTextField();
        jLabelDocumento = new javax.swing.JLabel();
        jCTextDocumento = new app.bolivia.swing.JCTextField();
        lblDatosBasicos2 = new javax.swing.JLabel();
        lblOtrosDatos = new javax.swing.JLabel();
        jLabelCorreoElectrinico = new javax.swing.JLabel();
        jCTextCorreoElectronico = new app.bolivia.swing.JCTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jCTextTelefono = new app.bolivia.swing.JCTextField();
        jLabelLocalidad = new javax.swing.JLabel();
        jCTextLocalidad = new app.bolivia.swing.JCTextField();
        jLabelDepartamento = new javax.swing.JLabel();
        jCTextDepartamento = new app.bolivia.swing.JCTextField();
        lblDatosDeContacto = new javax.swing.JLabel();
        jCTextContraseña = new app.bolivia.swing.JCTextField();
        jLabelContraseña = new javax.swing.JLabel();
        rSButtonGradienteModificarDatos = new rsbuttongradiente.RSButtonGradiente();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1320, 660));

        background.setAlignmentY(485.0F);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlePanel.setBackground(new java.awt.Color(0, 0, 0));
        titlePanel.setColorPrimario(new java.awt.Color(213, 240, 252));
        titlePanel.setColorSecundario(new java.awt.Color(105, 190, 228));
        titlePanel.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_3);

        lblTitle.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 51, 51));
        lblTitle.setText("Datos Personales");
        lblTitle.setPreferredSize(new java.awt.Dimension(92, 48));

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(681, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        background.add(titlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 1050, 120));

        sidePanel.setBackground(new java.awt.Color(105, 190, 228));
        sidePanel.setForeground(new java.awt.Color(105, 190, 228));
        sidePanel.setColorPrimario(new java.awt.Color(105, 190, 228));
        sidePanel.setColorSecundario(new java.awt.Color(105, 190, 228));
        sidePanel.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_3);

        imgUtecLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_1utec_logo.png"))); // NOI18N
        imgUtecLogo.setPreferredSize(new java.awt.Dimension(255, 155));

        btnUsuario.setBackground(new java.awt.Color(47, 165, 217));
        btnUsuario.setForeground(new java.awt.Color(105, 190, 228));

        imgBtnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_rsz_1rsz_1user_icon.png"))); // NOI18N

        lblBtnUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblBtnUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnUsuario.setText("Datos Personales");

        javax.swing.GroupLayout btnUsuarioLayout = new javax.swing.GroupLayout(btnUsuario);
        btnUsuario.setLayout(btnUsuarioLayout);
        btnUsuarioLayout.setHorizontalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUsuarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(imgBtnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBtnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        btnUsuarioLayout.setVerticalGroup(
            btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(btnUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblBtnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgBtnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(283, 283, 283))
        );

        btnReclamos.setBackground(new java.awt.Color(105, 190, 228));
        btnReclamos.setForeground(new java.awt.Color(105, 190, 228));

        imgBtnReclamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_1rsz_1reclamos-icon.png"))); // NOI18N

        lblBtnReclamos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblBtnReclamos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnReclamos.setText("Reclamos");

        btnInasistencias.setBackground(new java.awt.Color(105, 190, 228));
        btnInasistencias.setForeground(new java.awt.Color(105, 190, 228));

        imgBtnJustificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_rsz_justificacion-icon2.png"))); // NOI18N

        lblBtnJustificaciones.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblBtnJustificaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnJustificaciones.setText("Inasistencias");

        btnInasistencias1.setBackground(new java.awt.Color(105, 190, 228));
        btnInasistencias1.setForeground(new java.awt.Color(105, 190, 228));

        imgBtnJustificaciones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_rsz_justificacion-icon2.png"))); // NOI18N

        lblBtnJustificaciones1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lblBtnJustificaciones1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBtnJustificaciones1.setText("Justificaciones");

        javax.swing.GroupLayout btnInasistencias1Layout = new javax.swing.GroupLayout(btnInasistencias1);
        btnInasistencias1.setLayout(btnInasistencias1Layout);
        btnInasistencias1Layout.setHorizontalGroup(
            btnInasistencias1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInasistencias1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imgBtnJustificaciones1)
                .addGap(18, 18, 18)
                .addComponent(lblBtnJustificaciones1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnInasistencias1Layout.setVerticalGroup(
            btnInasistencias1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInasistencias1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnInasistencias1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBtnJustificaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgBtnJustificaciones1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout btnInasistenciasLayout = new javax.swing.GroupLayout(btnInasistencias);
        btnInasistencias.setLayout(btnInasistenciasLayout);
        btnInasistenciasLayout.setHorizontalGroup(
            btnInasistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnInasistenciasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imgBtnJustificaciones)
                .addGap(18, 18, 18)
                .addComponent(lblBtnJustificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(btnInasistencias1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnInasistenciasLayout.setVerticalGroup(
            btnInasistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnInasistenciasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnInasistenciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBtnJustificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgBtnJustificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInasistencias1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout btnReclamosLayout = new javax.swing.GroupLayout(btnReclamos);
        btnReclamos.setLayout(btnReclamosLayout);
        btnReclamosLayout.setHorizontalGroup(
            btnReclamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclamosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(imgBtnReclamos)
                .addGap(18, 18, 18)
                .addComponent(lblBtnReclamos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnInasistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnReclamosLayout.setVerticalGroup(
            btnReclamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReclamosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnReclamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBtnReclamos, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(lblBtnReclamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInasistencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReclamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(imgUtecLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 1, Short.MAX_VALUE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(imgUtecLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReclamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );

        background.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));
        background.add(jLabelRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelprimerApellido.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelprimerApellido.setText("Primer apellido:");
        jPanel2.add(jLabelprimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 31));

        jLabelPrimerNombre.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelPrimerNombre.setText("Primer nombre:");
        jPanel2.add(jLabelPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 65, -1, 31));

        jCTextFieldPrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextFieldPrimerNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextFieldPrimerNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 65, -1, -1));

        jCTextPrimerApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextPrimerApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jCTextFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 155, -1, -1));

        jLabelFechaDeNacimiento.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelFechaDeNacimiento.setText("Fecha de Nacimiento:");
        jPanel2.add(jLabelFechaDeNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 155, 149, 31));

        jLabelSegundoNombre.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelSegundoNombre.setText("Segundo nombre:");
        jPanel2.add(jLabelSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 65, 149, 31));

        jCTextSegundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextSegundoNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextSegundoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 65, -1, -1));

        jLabelSegundoApellido.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelSegundoApellido.setText("Segundo apellido:");
        jPanel2.add(jLabelSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 149, 31));

        jCTextSegundoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextSegundoApellidoActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        jLabelGenero.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelGenero.setText("Género:");
        jPanel2.add(jLabelGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 155, 149, 31));

        jCTextGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextGeneroActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 155, -1, -1));

        jLabelDocumento.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelDocumento.setText("Documento:");
        jPanel2.add(jLabelDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 149, 31));

        jCTextDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextDocumentoActionPerformed(evt);
            }
        });
        jPanel2.add(jCTextDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        lblDatosBasicos2.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblDatosBasicos2.setText("Datos básicos");
        jPanel2.add(lblDatosBasicos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 14, 162, -1));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        lblOtrosDatos.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblOtrosDatos.setText("Otros datos");
        background.add(lblOtrosDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 230, -1));

        jLabelCorreoElectrinico.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelCorreoElectrinico.setText("Correo electronico:");
        background.add(jLabelCorreoElectrinico, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 149, 31));

        jCTextCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextCorreoElectronicoActionPerformed(evt);
            }
        });
        background.add(jCTextCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelTelefono.setText("Teléfono:");
        background.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 149, 31));

        jCTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextTelefonoActionPerformed(evt);
            }
        });
        background.add(jCTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 440, -1, -1));

        jLabelLocalidad.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelLocalidad.setText("Localidad:");
        jLabelLocalidad.setAlignmentY(485.0F);
        background.add(jLabelLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 485, 149, 31));

        jCTextLocalidad.setAlignmentY(485.0F);
        jCTextLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextLocalidadActionPerformed(evt);
            }
        });
        background.add(jCTextLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 485, -1, -1));

        jLabelDepartamento.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelDepartamento.setText("Departamento:");
        background.add(jLabelDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 485, 149, 31));

        jCTextDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextDepartamentoActionPerformed(evt);
            }
        });
        background.add(jCTextDepartamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 485, -1, -1));

        lblDatosDeContacto.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblDatosDeContacto.setText("Datos de contacto");
        background.add(lblDatosDeContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 230, -1));

        jCTextContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTextContraseñaActionPerformed(evt);
            }
        });
        background.add(jCTextContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 610, -1, -1));

        jLabelContraseña.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña:");
        background.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, 149, 31));

        rSButtonGradienteModificarDatos.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonGradienteModificarDatos.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonGradienteModificarDatos.setText("MODIFICAR DATOS");
        rSButtonGradienteModificarDatos.setColorPrimario(new java.awt.Color(213, 240, 252));
        rSButtonGradienteModificarDatos.setColorPrimarioHover(new java.awt.Color(105, 190, 228));
        rSButtonGradienteModificarDatos.setColorSecundario(new java.awt.Color(105, 190, 228));
        rSButtonGradienteModificarDatos.setColorSecundarioHover(new java.awt.Color(213, 240, 252));
        rSButtonGradienteModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonGradienteModificarDatosActionPerformed(evt);
            }
        });
        background.add(rSButtonGradienteModificarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 602, 310, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1320, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1334, 697));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCTextDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextDocumentoActionPerformed

    private void jCTextGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextGeneroActionPerformed

    private void jCTextSegundoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextSegundoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextSegundoApellidoActionPerformed

    private void jCTextSegundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextSegundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextSegundoNombreActionPerformed

    private void jCTextFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextFechaNacimientoActionPerformed

    private void jCTextPrimerApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextPrimerApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextPrimerApellidoActionPerformed

    private void jCTextFieldPrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextFieldPrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextFieldPrimerNombreActionPerformed

    private void jCTextCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextCorreoElectronicoActionPerformed

    private void jCTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextTelefonoActionPerformed

    private void jCTextLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextLocalidadActionPerformed

    private void jCTextDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextDepartamentoActionPerformed

    private void jCTextContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTextContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTextContraseñaActionPerformed

    private void rSButtonGradienteModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonGradienteModificarDatosActionPerformed
        
    }//GEN-LAST:event_rSButtonGradienteModificarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPersonalesEstudiantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPersonalesEstudiantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel btnInasistencias;
    private javax.swing.JPanel btnInasistencias1;
    private javax.swing.JPanel btnReclamos;
    private javax.swing.JPanel btnUsuario;
    private javax.swing.JLabel imgBtnJustificaciones;
    private javax.swing.JLabel imgBtnJustificaciones1;
    private javax.swing.JLabel imgBtnReclamos;
    private javax.swing.JLabel imgBtnUsuario;
    private javax.swing.JLabel imgUtecLogo;
    private app.bolivia.swing.JCTextField jCTextContraseña;
    private app.bolivia.swing.JCTextField jCTextCorreoElectronico;
    private app.bolivia.swing.JCTextField jCTextDepartamento;
    private app.bolivia.swing.JCTextField jCTextDocumento;
    private app.bolivia.swing.JCTextField jCTextFechaNacimiento;
    private app.bolivia.swing.JCTextField jCTextFieldPrimerNombre;
    private app.bolivia.swing.JCTextField jCTextGenero;
    private app.bolivia.swing.JCTextField jCTextLocalidad;
    private app.bolivia.swing.JCTextField jCTextPrimerApellido;
    private app.bolivia.swing.JCTextField jCTextSegundoApellido;
    private app.bolivia.swing.JCTextField jCTextSegundoNombre;
    private app.bolivia.swing.JCTextField jCTextTelefono;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCorreoElectrinico;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelFechaDeNacimiento;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelPrimerNombre;
    private javax.swing.JLabel jLabelRuta;
    private javax.swing.JLabel jLabelSegundoApellido;
    private javax.swing.JLabel jLabelSegundoNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelprimerApellido;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBtnJustificaciones;
    private javax.swing.JLabel lblBtnJustificaciones1;
    private javax.swing.JLabel lblBtnReclamos;
    private javax.swing.JLabel lblBtnUsuario;
    private javax.swing.JLabel lblDatosBasicos2;
    private javax.swing.JLabel lblDatosDeContacto;
    private javax.swing.JLabel lblOtrosDatos;
    private javax.swing.JLabel lblTitle;
    private rsbuttongradiente.RSButtonGradiente rSButtonGradienteModificarDatos;
    private rspanelgradiente.RSPanelGradiente sidePanel;
    private rspanelgradiente.RSPanelGradiente titlePanel;
    // End of variables declaration//GEN-END:variables
}
